In [2]:
import numpy as np
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
j=0;
x=[]
for i in a:
    for j in i:  
        x.append(j)
print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [21]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
numOfRows = a.shape[0]
sum=0
for i in range (numOfRows):
    sum=sum+a[i,i]
print(sum)

12


In [29]:
y=int (input())
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
x=[]
for i in a:
    for j in i: 
        if j>y:
            x.append(j)
print (x)

5
[6, 7, 8]


In [3]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
b = np.array([[0,1,2],[3,4,5],[6,7,8]])
numOfRows = a.shape[0]
numOfCol=a.shape[1]
c= np.random.randint(0,10,(numOfRows,numOfCol))
for i in range(numOfRows):
    for j in range(numOfCol):
        c[i,j]=a[i,j]+b[i,j]
print(c)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [45]:
def sous_1D(a):
    sum=0
    num=a.shape[0]
    i=0;
    for i in range(0,num):
        sum=sum+a[i]
    return (sum/num)
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
numOfRows = a.shape[0]
numOfCol=a.shape[1]
for i in range(numOfRows):
    x=sous_1D(a[i])
    for j in range (numOfCol) :   
        a[i,j]=a[i,j]-x
        
print(a)

[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]
